---
title: "Formatting BCI 50 ha woody debris data"
author: "Lily Pitcher"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = here::here())
                       #"C:/Users/lilyp/OneDrive - Smithsonian Institution/Documents/D-woody debris/FILES FOR CODE")

```


```{r libraries}
#load in relevant packages
library(dplyr)
library(tidyr)
library(lubridate)
library(readxl)
library(openxlsx)
library(stringr)
library(here)
rm(list=ls())
```


```{r workingdirectory&filenames}
#load in relevant raw files and txt with new column names

FNRAW <- file.path("Dat0_Raw/CWD dynamics 40x40 2017.xlsx")
FNCOLNAMECHANGES <-"Corrections/colnamechange/colnamechanges_BCI2017.txt"

FSTEMFORMAT <-"Data1_Formatted/CWD40_2017"

```



```{r funcremovespecialchars}
#1. remove special characters function
removespecialchars <- function(stringvector) {
  stringvector <- gsub(",","",stringvector)
  stringvector <- gsub(" - ","_",stringvector)
  stringvector <- gsub(" ","_",stringvector)
  stringvector <- gsub("\\-","_",stringvector)
  stringvector <- gsub("\\?","",stringvector)
  stringvector <- gsub("\\(","",stringvector)
  stringvector <- gsub("\\)","",stringvector)
  stringvector <- gsub("á","a",stringvector)
  stringvector <- gsub("ó","o",stringvector)
  stringvector <- gsub("ú","u",stringvector)
  stringvector <- gsub("í","i",stringvector)
  stringvector <- gsub("ñ","n",stringvector)
  stringvector <- gsub("º","deg",stringvector)
  #stringvector <- gsub("NA","",stringvector)
  return(stringvector)
} # end removespecialchars


```


```{r funcfixcolnamesbysheet}

#2. fix column names
#function to apply new column names
fixcolnamesbysheet <- function(indata,sheetname="fallen", colnamefile=FNCOLNAMECHANGES) {
#load in file with column names
  thisnamechangeinfo <- read.table(colnamefile,header=T,encoding="UTF-8", sep="\t")
#filter for new names relating to relevant sheet/file
  thisnamechangeinfo <- subset(thisnamechangeinfo, sheet==sheetname)
  thisdata <- indata
#check for duplicates
  nperoldname <- table(thisnamechangeinfo$oldcolname)
  if (length(nperoldname[nperoldname>1])>0) 
    print(paste("WARNING: Column name corrections file",colnamefile ,"has multiple rows for column name",
                names(nperoldname)[nperoldname>1], "in sheet", sheetname))
#warning printed if a column in the file does not have a match
  matchcol <- match(names(thisdata),thisnamechangeinfo$oldcolname)
  if (length(matchcol[is.na(matchcol)])>0)
    print(paste("WARNING: Column name corrections file",colnamefile ,"has no match for column name",
                names(thisdata)[is.na(matchcol)],"in sheet",sheetname))
#assigns name from newcolumn when there is a match with oldcolumn
  for (j in 1:nrow(thisnamechangeinfo))
    names(thisdata)[names(thisdata)==thisnamechangeinfo$oldcolname[j]]<-thisnamechangeinfo$newcolname[j]
  nnewname <- table(names(thisdata))
  if (length(nnewname[nnewname>1])>0)
    print(paste("WARNING: After column name corrections from file",colnamefile ,"for sheet", sheetname,
                ", data table has multiple columns with column name",names(nnewname)[nnewname>1]))
  outdata <- thisdata
  return(outdata)
} 


```




```{r funcorrectdate}
#3. this function corrects for data in the form x.x that has been converted to dates by when filled out in the field and then back into a value/character when loaded into R, different from the original value (R converts to a five digit long value which represents the date as the number of days since Jan 01 1900 within the range 0f 40000 and 50000. )

fix_mistaken_dates <- function(indata) {
  sapply(indata, function(value) {
# Check if the value is a character, has a length of 5, and consists only of digits
    if (nchar(value) == 5 && grepl("^\\d+$", value)) {
# Convert the character to numeric
      numeric_value <- as.numeric(value)
          
# identify potential date conversion errors
      date_value <- tryCatch(
        as.Date(numeric_value, origin = "1899-12-30"),
        error = function(e) NA ) 
#  NA if date conversion fails
# Check if date_value is not NA
      if (!is.na(date_value)) {
# Extract day and month to to work out the original value
        day <- as.numeric(format(date_value, "%d"))
        month <- as.numeric(format(date_value, "%m"))
# Combine the day and month to form the original decimal (e.g., 7.1)
        return(as.numeric(paste0(day, ".", month)))
        } else {
# Return the original value unchanged if date conversion failed
          return(value)}
      } else {
# Return the original value unchanged if it doesn't meet the criteria
        return(value)
      }
    }
, simplify = TRUE)
  }

```

```{r fununiqueidnetifier}
#3. Add a unique identifier to each row 
##Fallen
GENERATE_UNIQID <- function(data, prefix = "item", pad = "") {
# Create a sequence of row numbers
  rownum <- seq(1, nrow(data))
  charrownum <- as.character(rownum)
  maxcharrownum <- max(nchar(charrownum))
# Apply padding based on the number of digits
  charrownum <- ifelse(nchar(charrownum) == maxcharrownum, charrownum,
                       ifelse(nchar(charrownum) == maxcharrownum - 1, paste0(pad, charrownum),
                       ifelse(nchar(charrownum) == maxcharrownum - 2, paste0(pad, pad, charrownum),
                       ifelse(nchar(charrownum) == maxcharrownum - 3, paste0(pad, pad, pad, charrownum),
                       paste0(pad, pad, pad, pad, charrownum)))))
# Create the uniqid column with the specified prefix
  data$uniqid <- paste0(prefix, charrownum)
  return(data)
  }

```

```{r funcolcombine}
#4. combining multiple notes columns
#some data has extra notes added in an additional column that is renamed to be notes2, this function pastes these extra notes into the original notes column (notes_new) and removes notes2column
combine_notes <- function(indata, col_notes_new, col_notes2) {
  indata <- indata %>%
#if two columns are present, paste them together into one.
    mutate(!!sym(col_notes_new) := ifelse(!is.na(!!sym(col_notes2)), 
                                        paste0(!!sym(col_notes_new), " ", !!sym(col_notes2)),
                                        !!sym(col_notes_new))) %>%
    select(-!!sym(col_notes2))
  outdata <- indata
  return(outdata)
  }

```



##Applying functions

Note assumption that the Excel file with the data has 3 sheets with data, ordered fallen, then standing, then less standing.  

```{r }
###### READ IN DATA FILES AND APPLY FUNCTIONS   ############
#For dynamic subplots: 
fallen <- read_excel(FNRAW,sheet=1)
standing <- read_excel(FNRAW, sheet = 2)
lessstanding <- read_excel(FNRAW, sheet = 3)


# 1. remove special characters 
names(fallen) <- removespecialchars(names(fallen))
names(standing) <- removespecialchars(names(standing))
names(lessstanding) <- removespecialchars(names(lessstanding))

#2. fix column names
fallen <- fixcolnamesbysheet(fallen,"fallen", FNCOLNAMECHANGES)
standing <- fixcolnamesbysheet(standing,"standing", FNCOLNAMECHANGES)
lessstanding <- fixcolnamesbysheet(lessstanding,"lessstanding", FNCOLNAMECHANGES)

```

```{r}
#3.unique id column
fallen<-GENERATE_UNIQID(fallen, "fallen", "0")
standing<-GENERATE_UNIQID(standing, "standing", "0")
lessstanding<-GENERATE_UNIQID(lessstanding, "lessstanding", "0")

#4. combine notes (only apply if neccessary)
  
fallen<-combine_notes(fallen, "notes_new", "notes2")
standing<-combine_notes(standing, "notes_new", "notes2")


```


```{r}
# FIXING SPECIFIC COLUMNS
# 5. fixing dates for specific columns known to have values that have been converted to dates
fallen[c("subplot_code", "code_of_piece")] <- lapply(fallen[c("subplot_code", "code_of_piece")], fix_mistaken_dates)
standing[c("subplot_code",   "code_of_piece", "height_new", "POM")] <- lapply(standing[c("subplot_code", "code_of_piece",   "height_new", "POM")], fix_mistaken_dates)
lessstanding[c("subplot_code", "code_of_piece",  "height", "POM")] <- lapply(lessstanding[c("subplot_code", "code_of_piece", "height", "POM")], fix_mistaken_dates)


#6.FORMATTING SPECIFIC COLOUMNS
    #A. Capitalize all the letters in transect_section_letter
#common error that transect sections are in lowercase and so converting them to upper case
fallen$transect_section_letter<-toupper(fallen$transect_section_letter)
standing$transect_section_letter<-toupper(standing$transect_section_letter)
lessstanding$transect_section_letter<-toupper(lessstanding$transect_section_letter)

    #B.Change formatting errors for consistency in code of piece
fallen <- fallen %>%
  mutate(code_of_piece =str_replace_all(code_of_piece, "[,.]", "-")) # Clean subplot_code
standing <- standing%>%
  mutate(code_of_piece = str_replace_all(code_of_piece, "[,.]", "-"))
lessstanding <- lessstanding %>%
  mutate(code_of_piece = str_replace_all(code_of_piece, "[,.]", "-"))

```




```{r duplicatecheck}
#8. check for duplicates
#Check how the rows are duplicated and identify which rows need to be deleted before adding them as files to delete in the corrections file (Blank=="y") to be removed later
fallen <- fallen[order(fallen$uniqid),]
#columns that if all match indicates a row is duplicated
checkcols <- c("year","tag","subplot_code","transect_section_letter","code_of_piece", "day","month","year")
dupes <- duplicated(fallen[,checkcols])
if (length(dupes[dupes==T])>0) {
  dupes2 <- duplicated(fallen[,checkcols],fromLast =TRUE) 
#check temp and check if there are duplicates, add copies to columns to remove in line by line corrections
  temp_fallen <- fallen[dupes|dupes2,] # get both copies of each duplicate 
  print(paste("Some rows are duplicates; check file",FNOUTDUPES))
}

standing <- standing[order (standing$uniqid),]
#columns that if all match indicates a row is duplicated
checkcols <- c("year","tag","subplot_code","transect_section_letter","code_of_piece", "day","month","year")
dupes <- duplicated(standing[,checkcols])
if (length(dupes[dupes==T])>0) {
  dupes2 <- duplicated(standing[,checkcols],fromLast =TRUE) 
#check temp and check if there are duplicates, add copies to columns to remove in line by line corrections
  temp_standing <- standing[dupes|dupes2,] # get both copies of each duplicate 
  print(paste("Some rows are duplicates; check file",FNOUTDUPES))
}


lessstanding <- lessstanding[order (lessstanding$uniqid),]
#columns that if all match indicates a row is duplicated
checkcols <- c("year","tag","subplot_code","transect_section_letter","code_of_piece", "day","month","year")
dupes <- duplicated(lessstanding[,checkcols])
if (length(dupes[dupes==T])>0) {
  dupes2 <- duplicated(lessstanding[,checkcols],fromLast =TRUE) 
#check temp and check if there are duplicates, add copies to columns to remove in line by line corrections
  temp_lessstanding <- lessstanding[dupes|dupes2,] # get both copies of each duplicate 
  print(paste("Some rows are duplicates; check file",FNOUTDUPES))
}
```



```{r generatingformatteddata}

#create txt files of the formatted data
write.table(fallen, file = "Data1_Formatted/CWD40_2015_fallen.txt", sep = "\t",  col.names = TRUE, row.names = FALSE)
write.table(standing, file = "Data1_Formatted/CWD40_2015_standing.txt",sep = "\t",   col.names = TRUE, row.names = FALSE)
write.table(lessstanding, file = "Data1_Formatted/CWD40_2010_lessstanding.txt", sep = "\t",  col.names = TRUE, row.names = FALSE)
```



















